# Generated by Django 5.0.1 on 2024-02-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='rollno',
            new_name='roll_no',
        ),
    ]
