# Generated by Django 5.0.1 on 2024-02-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rollno_score_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
