# Generated by Django 5.0.1 on 2024-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_score_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='roll_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
